### ISSUE TITLE
List of events

### ISSUE THREAD

**Issue by ghost** [Sharpjaws/SharpSK#14]
Hi I would like to know where the list of events of SharpSK are. In the documentation of skUnity there are just a list of conditions but not of events.

**Comment by Sharpjaws** [comment]
https://github.com/Sharpjaws/SharpSK/wiki/(W.I.P)Documentation

All the syntaxes are in the process of beign moved over to the new docs. That's why you can't find any event,effects,expression syntaxes from any addon in the docs. Meanwhile you can see some (most but not all) event syntaxes in the link above
