### ISSUE TITLE
On Extract (Question)

### ISSUE THREAD

**Issue by EverNife** [Sharpjaws/SharpSK#9]
How can i get the "event item" of this event.

I want to check if the item has a specific name so i can make a chance to delete the item.

**Comment by Sharpjaws** [comment]
You could already get the event-item from the event. However the problem is that it will always return the furnace which is not supposed to happen. This problem has been around for some time but this is an old bug that I simply forgot to fix. So I will make sure that this bug is patched in the next version

**Comment by EverNife** [comment]
^^
Ty very much
